version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: allanvargensDB
      MONGO_INITDB_ROOT_PASSWORD: vargens

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: allanvargensDB
      ME_CONFIG_MONGODB_ADMINPASSWORD: vargens
      ME_CONFIG_MONGODB_URL: mongodb://allanvargensDB:vargens@mongo:27017/